src/index.ts
test/fixtures/mailto/index.html
test/test.ts

Always skip `mailto:` links since they are not real links.

fix: skip mailto links

---

package.json
src/index.ts
test/test.ts

If a website contains a link to non-resolvable domain, it gets an exception from `fetch` and crashes.
Easy repro: `npx linkinator http://nonexistentdomain123zozozo.com`
Fixing that.

fix: do not crash on unresolved domain

---

package.json
src/links.ts

fix: properly calculate relative paths

---

src/links.ts
test/fixtures/image/index.html
test/test.ts

Added support for [srcset image attribute](https://developer.mozilla.org/docs/Web/HTML/Element/img#attr-srcset).
Parsing done like in [sindresorhus/srcset](https://github.com/sindresorhus/srcset/blob/master/index.js#L12).

 feat: add srcset attribute support

---

src/cli.ts

Hi @JustinBeckwith,
Thanks for your awesome tool 👍 
We appreciate it a lot at Bootstrap to check our docs.
My "issue" it's we have a lot of links and your tool output a lot of things, so I thought maybe it'll interest you to have a `silent` flag to just output broken links.
See how many links we have: https://travis-ci.org/twbs/bootstrap/jobs/528494120#L802 😄 
/CC @XhmikosR

feat(cli): add silent flag

---

.gitattributes

Without this, on Windows with `autocrlf: true` the files have CRLF.

build: enforce consistent git line endings

---

src/index.ts

This was a pretty straightforward change, but it allows for parsing of XHTML files. I tested it on a project to which I hope to incorporate linkinator.

feat: add support for xhtml

---

README.md
package.json
src/cli.ts
src/config.ts
src/index.ts
test/fixtures/config/linkinator.config.json
test/test.config.ts

Fixes #35.  This adds a `--concurrency` flag and config option that parallelizes requests.

feat: enable concurrent requests

---

README.md

docs: fix `recurse` key in README

---

src/index.ts
src/links.ts
test/fixtures/malformed/index.html
test/test.ts

fix: ignore all non-http[s] links

---

src/links.ts
test/fixtures/basetag/absolute.html
test/fixtures/basetag/empty-base.html
test/fixtures/basetag/relative-dot-folder.html
test/fixtures/basetag/relative-folder.html
test/fixtures/basetag/relative-page.html
test/fixtures/basetag/relative-to-root.html
test/test.ts

E-commerce sites uses base tag for static pages with nginx rewrites.
Supported cases: 
Usage of is-absolute-url (unfortunately by copy-paste) & URL can guarantee spec-compliant behaviour.

feat: HTML base tag support

---

README.md

The objects provided to the `link` event handler look like this:
```js
{
url: 'https://example.com/some-page',
status: 404,
state: 'OK',
parent: 'https://example.com/the-page-that-linked-to-it'
}
```
This PR updates the example in the README to mention the `parent` property.

docs: include result.parent property in README example

---

README.md
src/index.ts
test/fixtures/filter/index.html
test/test.ts

This PR adds a new `filterLinks` option to the `linkinator.check` function. The new option is a function that can be used to determine which URLs to skip and which to keep.
I'm not attached to the name of this option, nor the implementation. I'm open to alternatives ways of solving this that would expose the same level of flexibility to module users.

feat: add `filter` function as an option to linkinator.check()

---

package.json
test/mocha.opts

With current release of mocha, `npm test` prints a deprecation warning:
(node:10712) DeprecationWarning: Configuration via mocha.opts is
DEPRECATED and will be removed from a future version of Mocha. Use RC
files or package.json instead.
Move to package.json to eliminate the warning.

chore: replace deprecated mocha.opts with package.json config

---

.cirrus.yml
package.json
tsconfig.json

BREAKING CHANGE: This module now requires Node.js 10.x or greater.
Please upgrade to a LTS release of node.js.

build!: drop support for node.js 8.x

---

src/index.ts
test/test.ts

such as 'https://www.ebay.com.' This would cause link checking to fail for these sites. It seems like when it does a HEAD request on the site with a response type of 'stream,' it would get a bunch of redirects (over 100, which is the default for gaxios). Doing a simple GET request on the site worked correctly. We just need to make sure that we don't recursively crawl that site (opts.crawl should handle that).
I'm not 100% sure on response types and I did everything correctly, so it would be good to get another set of eyes on this.

fix: bug where it would fail urls that were valid

---

README.md
src/cli.ts
src/config.ts
src/index.ts
test/test.ts
test/zcli.ts

Adds a `--server-root` flag and corresponding API option to allow overriding the location on disk where the temporary web server is started.

feat: add --server-root flag

---

src/index.ts
test/test.ts

Pretty sure this fixes #209.  Previously, we weren't consistently sending the made up user agent.  When left alone, `node-fetch` likes to advertise itself.  Comically in #209, we can see that https://marketplace.visualstudio.com/items/DavidAnson.vscode-markdownlint is specifically rejecting user agents that include node-fetch (presumably to prevent the kind of scraping or link validation we're doing here).

fix: always send custom User-Agent

---

README.md
src/cli.ts
src/logger.ts
test/zcli.ts

Fixes #213.  This adds a `--verbosity` flag, which defaults to `WARNING`.  Skipped links now are hidden by default, unless verbosity is set to `INFO` or `DEBUG`.

feat: add verbosity flag to CLI

---

src/links.ts
test/fixtures/twittercard/index.html
test/test.ts

feat: scan opengraph and twittercard style meta links

---

src/cli.ts

Fixes https://github.com/JustinBeckwith/linkinator/issues/220, tests come later (this was a bad break)

fix: allow skip to be defined as an array

---

src/index.ts
src/options.ts
test/test.cli.ts
test/test.index.ts

Fixes https://github.com/JustinBeckwith/linkinator/issues/166.  This updates the returned paths in the results to map to the filesystem if a local path was given.

fix: map paths in results back to filesystem

---

.npmrc

The default setting is to always generate a package-lock.json file, so this step is required to prevent its generation.
For what is worth without the lock file we can't use caching properly on CI. Not that it's a huge deal, but it could speed things up a bit.

build: disable package-lock.json properly

---

README.md

* add newlines before/after code blocks and lists
* remove dollar sign from snippets since it makes copying harder and the commands don't have any output
* fix headings hierarchy
If you really want the dollar signs back let me know. It's just that it's common practice to not include them if there's no output and also it makes copying harder.

docs: README.md Markdown tweaks

---

.github/workflows/codeql.yml

CodeQL is the successor of [LGTM](https://lgtm.com). It checks for some common security issues.
Not sure if you have access to my fork actions/security tab so here's a screenshot:
Feel free to adapt the cron job and the branches :)

build: Add CodeQL scanning

---

.github/workflows/ci.yaml

When we are not on the upstream repo, don't run the release action
I was getting failures on my fork and it probably makes sense to skip the release action if not on upstream.

build: fix release action

---

.github/workflows/ci.yaml

* Add caching
* Run codecov only on Node.js 12
This is a little repetitive but currently actions don't allow us to reuse stuff. Opening to get an idea of the pros/cons. Should be significantly faster when there's a cache hit.

build: update CI config

---

package.json

I don't know of any way to reuse the bin script here in a cross-platform way, so this might be a little repetitive, but works everywhere and it's fast, without messing with the system.

build: remove `npm link` from `docs-test` too

---

test/test.index.ts

I split this from #244.
Note that I went with this solution so that I don't have to replace the `assert.rejects` methods. If you prefer to move everything to chai, let me know.

test: switch to `assert.match`

---

package.json

* html, so that we get nice browseable report, mostly useful locally
* text, for the CLI output
This should match the previous behavior + add the html reporter.

chore: add html reporter too in c8

---

.github/workflows/ci.yaml

Traditionally, I specified the fallback. Now, it depends on the project, if one prefers a cache miss or the cache growing.
There's also a third-party action, but I haven't used it in production yet: https://github.com/bahmutov/npm-install
It does seem to work, but it's another potential point of failure.
Let me know what you think.

build: remove the cache fallback

---

src/options.ts
src/server.ts
test/test.server.ts

Shout out to @dazuma who did the heavy lifting here, turns out I had to fix a weird windows path bug along the way, so landing here.

fix: handle querystring parameters in path

---

src/cli.ts
test/test.cli.ts

I suspect this is part of what's happening in https://github.com/JustinBeckwith/linkinator-action/issues/42

fix: do not include skipped links in the final link count

---

package-lock.json
package.json
src/links.ts

Refactor to use htmlparser2 which performs parsing in a single pass. _This is the same underlying parser used by cheerio._
This significantly increases the performance of parsing, here are the before and after timings for `nodejs-ai-platform` (_one of our repositories with the largest number of links:_)
**before:**
🤖 Successfully scanned 2166 links in 1267.81 seconds.
**after:**
🤖 Successfully scanned 2166 links in 407.295 seconds.

fix(perf): refactor to use htmlparser2

---

src/index.ts
src/links.ts

Before this fix, max mem usage scanning nodejs-ai-platform was ~3GB.  After, it was ~0.5GB.
Before:
```
npm run docs-test   513.31s  user 29.49s system 108% cpu 8:19.94 total
avg shared (code):         0 KB
avg unshared (data/stack): 0 KB
total (sum):               0 KB
max memory:                3016600 KB
page faults from disk:     0
other page faults:         9671141
```
After:
```
npm run docs-test   520.45s  user 26.06s system 110% cpu 8:14.96 total
avg shared (code):         0 KB
avg unshared (data/stack): 0 KB
total (sum):               0 KB
max memory:                561248 KB
page faults from disk:     0
other page faults:         7287496
```

fix(perf): use request streams to reduce memory usage

---

src/links.ts
test/fixtures/srcset/_site/bar.html
test/fixtures/srcset/_site/foo.html
test/fixtures/srcset/index.html
test/test.index.ts

Handling of `srcset` attribute was broken in migration to new parser.
Fixes #337

fix: special handling of srcset attribute

---

README.md
src/cli.ts
src/config.ts
src/index.ts
src/options.ts
test/test.retry.ts

Adds retry-errors option for retrying 5xx and network errors.
CC: @tmatsuo

feat: add retry-errors option

---

src/cli.ts
src/index.ts
src/queue.ts
test/test.retry.ts

* Adds an exponential backoff rather than just a random delay, which I think is more likely to avoid errors.
* Increases default retries to 5, so that the default maximum retry delay will be 30s (starting at 2s).
* Adds test that retries terminate.
* Partially address painful bug I bumped into trying to write tests.

feat: exponential backoff

---

src/index.ts

Managed to reproduce `[0]` crawl issue locally using the following test repository:
https://github.com/bcoe/external-link-repo
Designed specifcially to trigger the bug.
----
tldr; there was a slight bug with the retry logic, rather than retrying failed links, it was only caching one entry per host. This meant that when a burst of errors occurred, we would immediately hit the stop condition and not actually retry the failed URLs.
I have not been able to recreate the failure when running locally with this fix.

fix: retry on href not host

---

.github/workflows/ci.yaml

Due to https://github.com/vercel/pkg/issues/1291, the build is current broken.  This disables those builds until the underlying issue can be fixed.

build: disable binary builds

---

package-lock.json
package.json
src/cli.ts
test/test.cli.ts
test/test.retry.ts

Fixes #498.  Instead of building up all CSV results until the end, the CLI will now stream the results as they come in.  This does mean moving from [jsonexport](https://www.npmjs.com/package/jsonexport) to a custom CSV generator, which could in theory be a breaking change for someone.

fix!: stream CSV results

---

src/links.ts
test/fixtures/srcset/index.html

Fixes #511.  This is a hack to paper over a bug in the npm module srcset:
https://github.com/sindresorhus/srcset/issues/14

fix: address srcset parsing with multiple spaces

---

package-lock.json
package.json
src/cli.ts

Hey @JustinBeckwith, how are you doing? :)
Let's drop `update-notifier` (at least for now), since some types got broken deep in the dependencies and I don't really want to go fix it down there.
What we see is:
```
node_modules/@types/cacheable-request/index.d.ts:26:42 - error TS2709: Cannot use namespace 'ResponseLike' as a type.
26         cb?: (response: ServerResponse | ResponseLike) => void
~~~~~~~~~~~~
node_modules/@types/cacheable-request/index.d.ts:77:51 - error TS2709: Cannot use namespace 'ResponseLike' as a type.
77             listener: (response: ServerResponse | ResponseLike) => void
~~~~~~~~~~~~
```
I see you already dropped `update-notifier` from `gts`, so maybe just do the same here, what do you think?

fix: remove update-notifier

---

src/config.ts
test/fixtures/config/linkinator.config.cjs
test/fixtures/config/linkinator.config.invalid.json
test/fixtures/config/linkinator.config.js
test/fixtures/config/linkinator.config.mjs
test/test.config.ts

Add support for JS based config file like .js, .mjs & .cjs
- In `config.ts` added following functions
- `getTypeOfConfig()` - for extract the file extension of config file & throw exception on invalid extension
- `importConfigFile()` - for importing javascript config files
- `readJsonConfigFile()` - for reading & parsing JSON based config file
- `parseConfigFile()` - parent function encapsulating the logic to detect & call right function to load the config based on type
- Default format of config file is considered as JSON if no extension is provided, so as to maintain backward compatibility
Fixes: #504

feat(Config): Support for Javascript based config files

---

src/cli.ts
src/config.ts

The `file://` prefix on the dynamic import statement for config was breaking ncc in `linkinator-action`.  The tests still pass with this change, and it appears to still work ..... 🤷

fix: remove file import prefix to please ncc

---

.github/workflows/ci.yaml
package.json

BREAKING CHANGE: Now requires node.js 16 or higher

feat!: require node.js 16 and up

---

.eslintignore
.eslintrc.json
.github/workflows/ci.yaml
.prettierignore
.prettierrc.json
README.md
package-lock.json
package.json
samples/api.js
src/cli.ts
src/config.ts
src/index.ts
src/links.ts
src/logger.ts
src/options.ts
src/queue.ts
src/server.ts
test/fixtures/config/linkinator.config.cjs
test/fixtures/config/linkinator.config.js
test/fixtures/config/linkinator.config.mjs
test/fixtures/scripts/script.js
test/test.cli.ts
test/test.config.ts
test/test.index.ts
test/test.retry.ts
test/test.server.ts
tsconfig.json

BREAKING CHANGE: This module now requires node.js 18 and up.  It includes a variety of related changes:
- Migrate from gts to xo for linting and code formatting
- Upgrade multiple deps to the latest version that were blocked on node 16
- Drop the codecov dependency and move to the github action
- Update the tsconfig to target Node16 for the module strategy
It's entirely possible this change didn't break anything for most users, but it's also possible it did.

build!: drop support for node 16

---

tsconfig.json

Hi @JustinBeckwith!  I noticed that since `6.0.0` there were no `.d.ts` files generated anymore into the build folder.
I found out it was because of [this line](https://github.com/JustinBeckwith/linkinator/commit/351a7c9ebf46d48a5d05b51d8c390f398eba6af1#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0L2). Because of that config missing, we lost `"declaration": true`.
If this was not intended, maybe it's worth adding it? Thanks!

fix: add declaration true to compilerOptions to generate d.ts files

---

src/config.ts
src/index.ts
test/fixtures/defaultconfig/index.html
test/fixtures/defaultconfig/linkinator.config.json
test/test.cli.ts

Fixes #600.  Turns out this never actually worked 😭

fix(cli): load linkinator.config.json by default

---

package-lock.json
package.json
src/index.ts
test/test.cli.ts
test/test.index.ts
test/test.retry.ts
test/test.server.ts
vitest.config.ts

This changes the underlying HTTP transport mechanism from `gaxios` to native `fetch` built on `undici`.  The tests have been updated to use `undici` mock transport instead of nock.

fix: migrate from gaxios to undici
