JustinBeckwith/linkinator

src/index.ts, test/fixtures/recurse/fake.html, test/test.ts
=> fix: send a HEAD instead of GET at first

src/index.ts, test/fixtures/scripts/index.html, test/fixtures/scripts/script.js, test/test.ts
=> fix: skip scanning non-html files

src/cli.ts
=> fix: print the stats even after a fail

src/index.ts, test/fixtures/relative/index.html, test/fixtures/relative/nested/index.html, test/fixtures/relative/nested/nested.html, test/test.ts
=> fix: calc relative paths based on current url

README.md, package.json, samples/api.js
=> docs: add API reference and examples

src/links.ts, test/fixtures/malformed/index.html, test/test.ts
Relates to: https://github.com/googleapis/nodejs-dataproc/pull/171
=> fix: add try/catch for malformed links

.ci/docker/windows/Dockerfile, .cirrus.yml, package.json, src/index.ts
Fixes #60.  
Good news: now we are testing this!
Bad news: the tests all fail 😆
=> build: run tests on windows

LICENSE.md, README.md, package.json, src/cli.ts
=> fix: resolve conflict with -s short flag

src/index.ts, test/fixtures/protocols/index.html, test/test.ts
=> fix: do not follow irc links

src/index.ts, test/fixtures/mailto/index.html, test/fixtures/protocols/index.html, test/test.ts
=> fix: do not follow data URIs

src/index.ts, src/links.ts, test/fixtures/baseurl/index.html, test/test.ts
=> fix: only crawl exact host matches

src/cli.ts
=> fix: stringify js for json

src/index.ts, src/links.ts
This change reduces top memory consumption of the module by 20% when run against nodejs-vision.
=> fix(perf): reduce total memory consumption

README.md, src/cli.ts, src/config.ts, src/index.ts, test/test.config.ts, test/test.ts
=> feat: add timeout config option

src/cli.ts, src/index.ts, test/test.ts, test/zcli.ts
=> feat: expose error details when verbosity=DEBUG

src/cli.ts, src/logger.ts, test/zcli.ts
=> fix: follow verbosity rules for JSON and CSV

src/index.ts, test/fixtures/nested/doll1/index.html, test/fixtures/nested/doll2/index.html, test/test.ts
=> fix: resolve glob paths based on server root

.github/workflows/ci.yaml
* move Node.js version to an environment variable
* update to `actions/setup-node@v2`
=> build: update CI config

test/test.cli.ts
Fixes #245 maybe.  Makes @XhmikosR and their windows machine happier 🙃 Only risk here is not entirely covering the way CLI is tested with the package.
=> test: stop using npm link in CLI tests

.github/workflows/ci.yaml
=> CI: add caching for Windows too

README.md
=> chore: README.md: remove `.svg` from badges

.github/workflows/ci.yaml, package-lock.json, package.json, test/test.cli.ts
The commit message should probably be `build,tests` or something
=> build: CI: specify `FORCE_COLOR: 2`

package.json, src/queue.ts, test/test.retry.ts
Slightly more elegant approach for handling infinite loops caused by schreduling hiccups.
=> feat: add cleanup setInterval()

README.md
=> docs: update format of the config file

src/options.ts, test/test.index.ts
=> fix: allow server root with trailing slash

SECURITY.md
Though maybe you'd just want to take "(3.x)" out to avoid having to update it?
=> docs: Update latest major version specified in SECURITY.md

README.md, src/cli.ts, src/config.ts, test/test.cli.ts
Fixes https://github.com/JustinBeckwith/linkinator/issues/384
=> feat: allow --skip to be defined multiple times

package-lock.json, package.json, src/links.ts, test/test.server.ts
The change in which mime type it detects is a little sketchy, but I don't believe browsers really differentiate between the two types.
=> fix: upgrade to mime v4

src/index.ts
=> chore: update comment to reflect reason for retry

README.md, src/cli.ts, src/index.ts, src/options.ts, test/test.index.ts
=> feat: add option for setting user agent

src/cli.ts, test/fixtures/localbroke/README.md, test/test.cli.ts
=> fix: JSON stringify failure details for CSV

package-lock.json, package.json
Fixes https://github.com/JustinBeckwith/linkinator/issues/663.  
Weird that my CI didn't detect any problems here with it, but yeah I should do the semver major upgrade to drop node 18 first
=> fix(deps): revert back to marked 13

README.md, src/cli.ts
fixes https://github.com/JustinBeckwith/linkinator/issues/619
=> docs: better document multiple skips

.github/workflows/ci.yaml, README.md, package.json
Fixes https://github.com/JustinBeckwith/linkinator/issues/361
=> feat: re-enable binary releases

src/index.ts, test/test.index.ts
fixes https://github.com/JustinBeckwith/linkinator/issues/529
=> fix: handle trailing slash on redirects
